/* Automatically generated by '../script/build-entry.js' */
import fInput from './input/index.js';
import fSelect from './select/index.js';
import fInputs from './inputs/index.js';
import fMessage from './message/index.js';
// 版本号
import pkg from '../package.json'


const components = [
    fInput,
  fSelect,
  fInputs
];

const install = (app) => {
  components.forEach((i) => {
    app.use(i)
  })
    app.config.globalProperties.$Message = fMessage
}

const fxUi = {
  version: pkg.version,
  install
}

export {
  install,
    fInput,
  fSelect,
  fInputs,
  fMessage
}

export default fxUi
